# this is a github action that runs the python build

name: mafia_level0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted , windows, x64]
    steps:
      - uses: actions/checkout@v2
      - name: BIG_CORE
        run:  python build.py -dut big_core -test alive -app -hw -sim 

      - name: CORE_RRV - rv32i
        run:  python build.py -dut core_rrv -test alive -app -hw -sim -pp 
      
      - name: CORE_RRV - -cfg core_rrv_boot_trap no reference model
        run:  python build.py -dut core_rrv -top core_rrv_no_ref_tb -cfg core_rrv_boot_trap -test PS2_alive.c  -app -hw -sim -pp 
      
      - name: CORE_RRV -cfg core_rrv_boot_trap with reference model
        run:  python build.py -dut core_rrv -cfg core_rrv_boot_trap -test alive_illegal.c -app -hw -sim -pp 

      - name: MINI_CORE at rv32e mode
        run:  python build.py -dut mini_core -test alive -cfg mini_rv32e -app -hw -sim 

      - name: MINI_CORE at rv32i mode
        run:  python build.py -dut mini_core -test alive -app -hw -sim 

      - name: SC_CORE 
        run:  python build.py -dut sc_core -test alive -app -hw -sim 

      - name: D_CACHE
        run: python build.py -dut mem_ss -top cache_tb -test cache_alive -hw -sim -pp 

      - name: ROUTER 
        run:  python build.py -dut fabric -top router_tb -test router_alive -hw -sim 

      - name: FABRIC 
        run:  python build.py -dut fabric -test fabric_alive -hw -sim 