# this is a github action that runs the python build

name: mafia_sanity

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted , windows, x64]
    steps:
      - uses: actions/checkout@v2
      - name: BIG_CORE - all
        run:  python build.py -dut 'big_core' -regress level0 -app -hw -sim -keep_going

      - name: CORE_RRV - rv32i_level0 
        run:  python build.py -dut core_rrv -regress rv32i_level0 -app -hw -sim -pp -keep_going
      
      - name: CORE_RRV - rv32i_level0_cfg_intrpt -cfg core_rrv_boot_trap no reference model
        run:  python build.py -dut core_rrv -top core_rrv_no_ref_tb -cfg core_rrv_boot_trap -regress rv32i_level0_cfg_intrpt_no_ref -app -hw -sim -pp -keep_going
      
      - name: CORE_RRV - rv32i_level0_cfg_intrpt -cfg core_rrv_boot_trap with reference model
        run:  python build.py -dut core_rrv -cfg core_rrv_boot_trap -regress rv32i_level0_cfg_intrpt -app -hw -sim -pp -keep_going

      - name: MINI_CORE at rv32e mode
        run:  python build.py -dut 'mini_core' -regress rv32e_level0 -cfg mini_rv32e -app -hw -sim -keep_going

      - name: MINI_CORE at rv32i mode
        run:  python build.py -dut 'mini_core' -regress rv32i_level0 -app -hw -sim -keep_going

      - name: SC_CORE - rv32i_level0 
        run:  python build.py -dut sc_core -regress rv32i_level0 -app -hw -sim -keep_going

      - name: D_CACHE level0_d_cache
        run: python build.py -dut 'mem_ss' -top cache_tb -regress cache_alive -hw -sim -pp -keep_going

      - name: I_CACHE -regress level0_i_cache
        run:  python build.py -dut 'mem_ss' -top cache_tb -regress level0_i_cache -hw -sim -pp -keep_going

      - name: ROUTER -regress level0
        run:  python build.py -dut 'fabric' -top router_tb -regress router_level0 -hw -sim -keep_going

      - name: FABRIC -regress level0
        run:  python build.py -dut 'fabric' -regress level0 -hw -sim -keep_going