# this is a github action that runs the python build

name: mafia_sanity_2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted , windows, x64]
    steps:
      - uses: actions/checkout@v2
      - name: Run build on bash take2
        run: python build.py -proj_name 'big_core' -debug -tests alive -app -hw -sim

